logging:
  level:
    root: INFO
    org.quartz: INFO

myth-cloth-market-service:
  crawler:
    playwright:
      channel: ${PLAYWRIGHT_CHANNEL:chrome}
      executable-path: ${PLAYWRIGHT_EXECUTABLE_PATH:/usr/bin/google-chrome}
      args:
        - "--no-sandbox"
        - "--disable-dev-shm-usage"
    jobs:
      - key: "NIN_NIN_GAME"
        name: "Nin Nin Game Crawler"
        cron: ${NIN_NIN_GAME_CRON:0 0 7 * * ?}
        enabled: true

      - key: "MANDARAKE"
        name: "Mandarake Crawler"
        cron: ${MANDARAKE_CRON:0 0 8 * * ?}
        enabled: true

      - key: "LUNA_PARK"
        name: "Luna Park Crawler"
        cron: ${LUNA_PARK_CRON:0 0 9 * * ?}
        enabled: true

      - key: "MY_KOMBINI"
        name: "My Kombini Crawler"
        cron: ${MY_KOMBINI_CRON:0 0 10 * * ?}
        enabled: true

      - key: "MYTH_SUPPLIES"
        name: "Myth Supplies Crawler"
        cron: ${MYTH_SUPPLIES_CRON:0 0 11 * * ?}
        enabled: true

      - key: "LOGAN_STORE"
        name: "Logan Store Crawler"
        cron: ${LOGAN_STORE_CRON:0 0 12 * * ?}
        enabled: true

      - key: "MYTH_FACTORY"
        name: "Myth Factory Crawler"
        cron: ${MYTH_FACTORY_CRON:0 0 13 * * ?}
        enabled: true

spring:

  rabbitmq:
    port: ${RABBITMQ_PORT}
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST}
    ssl:
      enabled: true
