logging:
  level:
    root: INFO
    org.quartz: DEBUG

myth-cloth-market-service:
  crawler:
    jobs:
      - key: "NIN_NIN_GAME"
        name: "Nin Nin Game Crawler"
        cron: "0 * * * * ?" # Every 2 hours
        enabled: false

      - key: "MANDARAKE"
        name: "Mandarake Crawler"
        cron: "0 0 9 * * ?"   # Every day at 9 AM
        enabled: false

      - key: "LUNA_PARK"
        name: "Luna Park Crawler"
        cron: "0 0 12 * * ?"   # Every day at noon
        enabled: false

      - key: "MY_KOMBINI"
        name: "My Kombini Crawler"
        cron: "0 0 11 * * ?"   # Every day at 11 AM
        enabled: false

spring:
  rabbitmq:
    host: localhost
    username: mythcloth
    password: mythcloth
