management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always

myth-cloth-market-service:

server:
  servlet:
    context-path: /

spring:
  application:
    name: myth-cloth-market-service
