logging:
  level:
    root: INFO
    org.quartz: DEBUG

myth-cloth-market-service:
  crawler:
    jobs:
      - key: "NIN_NIN_GAME"
        name: "Nin Nin Game Crawler"
        cron: "0 0 7 * * ?" # Every day at 7:00
        enabled: false

      - key: "MANDARAKE"
        name: "Mandarake Crawler"
        cron: "0 0 8 * * ?" # Every day at 8:00
        enabled: false

      - key: "LUNA_PARK"
        name: "Luna Park Crawler"
        cron: "0 0 9 * * ?" # Every day at 9:00
        enabled: false

      - key: "MY_KOMBINI"
        name: "My Kombini Crawler"
        cron: "0 0 10 * * ?" # Every day at 10:00
        enabled: false

      - key: "MYTH_SUPPLIES"
        name: "Myth Supplies Crawler"
        cron: "0 0 11 * * ?" # Every day at 11:00
        enabled: false

      - key: "LOGAN_STORE"
        name: "Logan Store Crawler"
        cron: "0 0 12 * * ?" # Every day at 12:00
        enabled: false

      - key: "MYTH_FACTORY"
        name: "Myth Factory Crawler"
        cron: "0 0 13 * * ?" # Every day at 13:00
        enabled: false

spring:
  rabbitmq:
    host: localhost
    username: mythcloth
    password: mythcloth
