management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always

myth-cloth-market-service:

server:
  servlet:
    context-path: /api/v1

spring:
  application:
    name: myth-cloth-market-service
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MythClothMarketServiceScheduler
            instanceId: AUTO
          threadPool:
            threadCount: 5
